// Ordinarily, you'd generate this data from markdown files in your
// repo, or fetch them from a database of some kind. But in order to
// avoid unnecessary dependencies in the starter template, and in the
// service of obviousness, we're just going to leave it here.

// This file is called `_posts.js` rather than `posts.js`, because
// we don't want to create an `/blog/posts` route — the leading
// underscore tells Sapper not to do that.

const counties = [
  {"slug":"jefferson-alabama","cases":"305","deaths":"4","county":"Jefferson","state":"Alabama"},
  {"slug":"maricopa-arizona","cases":"871","deaths":"8","county":"Maricopa","state":"Arizona"},
  {"slug":"pima-arizona","cases":"217","deaths":"10","county":"Pima","state":"Arizona"},
  {"slug":"alameda-california","cases":"380","deaths":"8","county":"Alameda","state":"California"},
  {"slug":"contracosta-california","cases":"250","deaths":"3","county":"Contra Costa","state":"California"},
  {"slug":"losangeles-california","cases":"3518","deaths":"65","county":"Los Angeles","state":"California"},
  {"slug":"orange-california","cases":"606","deaths":"10","county":"Orange","state":"California"},
  {"slug":"riverside-california","cases":"371","deaths":"13","county":"Riverside","state":"California"},
  {"slug":"sacramento-california","cases":"314","deaths":"9","county":"Sacramento","state":"California"},
  {"slug":"sanbernardino-california","cases":"254","deaths":"6","county":"San Bernardino","state":"California"},
  {"slug":"sandiego-california","cases":"849","deaths":"15","county":"San Diego","state":"California"},
  {"slug":"sanfrancisco-california","cases":"437","deaths":"7","county":"San Francisco","state":"California"},
  {"slug":"sanmateo-california","cases":"388","deaths":"10","county":"San Mateo","state":"California"},
  {"slug":"santaclara-california","cases":"956","deaths":"33","county":"Santa Clara","state":"California"},
  {"slug":"adams-colorado","cases":"214","deaths":"6","county":"Adams","state":"Colorado"},
  {"slug":"arapahoe-colorado","cases":"381","deaths":"7","county":"Arapahoe","state":"Colorado"},
  {"slug":"denver-colorado","cases":"586","deaths":"8","county":"Denver","state":"Colorado"},
  {"slug":"eagle-colorado","cases":"295","deaths":"4","county":"Eagle","state":"Colorado"},
  {"slug":"elpaso-colorado","cases":"314","deaths":"14","county":"El Paso","state":"Colorado"},
  {"slug":"jefferson-colorado","cases":"356","deaths":"7","county":"Jefferson","state":"Colorado"},
  {"slug":"weld-colorado","cases":"293","deaths":"13","county":"Weld","state":"Colorado"},
  {"slug":"fairfield-connecticut","cases":"1986","deaths":"38","county":"Fairfield","state":"Connecticut"},
  {"slug":"hartford-connecticut","cases":"469","deaths":"8","county":"Hartford","state":"Connecticut"},
  {"slug":"newhaven-connecticut","cases":"611","deaths":"12","county":"New Haven","state":"Connecticut"},
  {"slug":"newcastle-delaware","cases":"226","deaths":"6","county":"New Castle","state":"Delaware"},
  {"slug":"districtofcolumbia-districtofcolumbia","cases":"586","deaths":"11","county":"District of Columbia","state":"District of Columbia"},
  {"slug":"broward-florida","cases":"1348","deaths":"13","county":"Broward","state":"Florida"},
  {"slug":"duval-florida","cases":"239","deaths":"4","county":"Duval","state":"Florida"},
  {"slug":"hillsborough-florida","cases":"362","deaths":"3","county":"Hillsborough","state":"Florida"},
  {"slug":"lee-florida","cases":"235","deaths":"10","county":"Lee","state":"Florida"},
  {"slug":"miami-dade-florida","cases":"2415","deaths":"11","county":"Miami-Dade","state":"Florida"},
  {"slug":"orange-florida","cases":"458","deaths":"3","county":"Orange","state":"Florida"},
  {"slug":"palmbeach-florida","cases":"616","deaths":"22","county":"Palm Beach","state":"Florida"},
  {"slug":"pinellas-florida","cases":"233","deaths":"5","county":"Pinellas","state":"Florida"},
  {"slug":"cobb-georgia","cases":"304","deaths":"15","county":"Cobb","state":"Georgia"},
  {"slug":"dekalb-georgia","cases":"360","deaths":"4","county":"DeKalb","state":"Georgia"},
  {"slug":"dougherty-georgia","cases":"490","deaths":"29","county":"Dougherty","state":"Georgia"},
  {"slug":"fulton-georgia","cases":"638","deaths":"20","county":"Fulton","state":"Georgia"},
  {"slug":"gwinnett-georgia","cases":"257","deaths":"6","county":"Gwinnett","state":"Georgia"},
  {"slug":"unknown-georgia","cases":"485","deaths":"2","county":"Unknown","state":"Georgia"},
  {"slug":"ada-idaho","cases":"226","deaths":"3","county":"Ada","state":"Idaho"},
  {"slug":"blaine-idaho","cases":"265","deaths":"2","county":"Blaine","state":"Idaho"},
  {"slug":"cook-illinois","cases":"5152","deaths":"95","county":"Cook","state":"Illinois"},
  {"slug":"dupage-illinois","cases":"392","deaths":"12","county":"DuPage","state":"Illinois"},
  {"slug":"lake-illinois","cases":"477","deaths":"7","county":"Lake","state":"Illinois"},
  {"slug":"will-illinois","cases":"322","deaths":"9","county":"Will","state":"Illinois"},
  {"slug":"marion-indiana","cases":"1117","deaths":"21","county":"Marion","state":"Indiana"},
  {"slug":"jefferson-kentucky","cases":"221","deaths":"8","county":"Jefferson","state":"Kentucky"},
  {"slug":"caddo-louisiana","cases":"298","deaths":"7","county":"Caddo","state":"Louisiana"},
  {"slug":"eastbatonrouge-louisiana","cases":"244","deaths":"10","county":"East Baton Rouge","state":"Louisiana"},
  {"slug":"jefferson-louisiana","cases":"1433","deaths":"64","county":"Jefferson","state":"Louisiana"},
  {"slug":"orleans-louisiana","cases":"2270","deaths":"115","county":"Orleans","state":"Louisiana"},
  {"slug":"st.tammany-louisiana","cases":"270","deaths":"6","county":"St. Tammany","state":"Louisiana"},
  {"slug":"baltimore-maryland","cases":"289","deaths":"1","county":"Baltimore","state":"Maryland"},
  {"slug":"montgomery-maryland","cases":"447","deaths":"1","county":"Montgomery","state":"Maryland"},
  {"slug":"princegeorge's-maryland","cases":"403","deaths":"7","county":"Prince George's","state":"Maryland"},
  {"slug":"barnstable-massachusetts","cases":"255","deaths":"3","county":"Barnstable","state":"Massachusetts"},
  {"slug":"bristol-massachusetts","cases":"366","deaths":"3","county":"Bristol","state":"Massachusetts"},
  {"slug":"essex-massachusetts","cases":"885","deaths":"17","county":"Essex","state":"Massachusetts"},
  {"slug":"hampden-massachusetts","cases":"475","deaths":"17","county":"Hampden","state":"Massachusetts"},
  {"slug":"middlesex-massachusetts","cases":"1582","deaths":"21","county":"Middlesex","state":"Massachusetts"},
  {"slug":"norfolk-massachusetts","cases":"829","deaths":"15","county":"Norfolk","state":"Massachusetts"},
  {"slug":"plymouth-massachusetts","cases":"561","deaths":"5","county":"Plymouth","state":"Massachusetts"},
  {"slug":"suffolk-massachusetts","cases":"1624","deaths":"14","county":"Suffolk","state":"Massachusetts"},
  {"slug":"unknown-massachusetts","cases":"335","deaths":"5","county":"Unknown","state":"Massachusetts"},
  {"slug":"worcester-massachusetts","cases":"563","deaths":"9","county":"Worcester","state":"Massachusetts"},
  {"slug":"genesee-michigan","cases":"249","deaths":"8","county":"Genesee","state":"Michigan"},
  {"slug":"macomb-michigan","cases":"1088","deaths":"51","county":"Macomb","state":"Michigan"},
  {"slug":"oakland-michigan","cases":"1910","deaths":"99","county":"Oakland","state":"Michigan"},
  {"slug":"washtenaw-michigan","cases":"401","deaths":"8","county":"Washtenaw","state":"Michigan"},
  {"slug":"wayne-michigan","cases":"4470","deaths":"146","county":"Wayne","state":"Michigan"},
  {"slug":"hennepin-minnesota","cases":"218","deaths":"6","county":"Hennepin","state":"Minnesota"},
  {"slug":"st.louis-missouri","cases":"492","deaths":"3","county":"St. Louis","state":"Missouri"},
  {"slug":"clark-nevada","cases":"961","deaths":"28","county":"Clark","state":"Nevada"},
  {"slug":"bergen-newjersey","cases":"3494","deaths":"75","county":"Bergen","state":"New Jersey"},
  {"slug":"burlington-newjersey","cases":"255","deaths":"5","county":"Burlington","state":"New Jersey"},
  {"slug":"camden-newjersey","cases":"289","deaths":"3","county":"Camden","state":"New Jersey"},
  {"slug":"essex-newjersey","cases":"2262","deaths":"69","county":"Essex","state":"New Jersey"},
  {"slug":"hudson-newjersey","cases":"1910","deaths":"29","county":"Hudson","state":"New Jersey"},
  {"slug":"mercer-newjersey","cases":"333","deaths":"3","county":"Mercer","state":"New Jersey"},
  {"slug":"middlesex-newjersey","cases":"1493","deaths":"27","county":"Middlesex","state":"New Jersey"},
  {"slug":"monmouth-newjersey","cases":"1301","deaths":"24","county":"Monmouth","state":"New Jersey"},
  {"slug":"morris-newjersey","cases":"942","deaths":"25","county":"Morris","state":"New Jersey"},
  {"slug":"ocean-newjersey","cases":"1209","deaths":"23","county":"Ocean","state":"New Jersey"},
  {"slug":"passaic-newjersey","cases":"1494","deaths":"15","county":"Passaic","state":"New Jersey"},
  {"slug":"somerset-newjersey","cases":"472","deaths":"15","county":"Somerset","state":"New Jersey"},
  {"slug":"union-newjersey","cases":"1661","deaths":"29","county":"Union","state":"New Jersey"},
  {"slug":"unknown-newjersey","cases":"4512","deaths":"7","county":"Unknown","state":"New Jersey"},
  {"slug":"albany-newyork","cases":"240","deaths":"2","county":"Albany","state":"New York"},
  {"slug":"dutchess-newyork","cases":"547","deaths":"5","county":"Dutchess","state":"New York"},
  {"slug":"erie-newyork","cases":"553","deaths":"12","county":"Erie","state":"New York"},
  {"slug":"monroe-newyork","cases":"349","deaths":"9","county":"Monroe","state":"New York"},
  {"slug":"nassau-newyork","cases":"9555","deaths":"76","county":"Nassau","state":"New York"},
  {"slug":"newyorkcity-newyork","cases":"47440","deaths":"1374","county":"New York City","state":"New York"},
  {"slug":"onondaga-newyork","cases":"249","deaths":"1","county":"Onondaga","state":"New York"},
  {"slug":"orange-newyork","cases":"1756","deaths":"25","county":"Orange","state":"New York"},
  {"slug":"putnam-newyork","cases":"207","deaths":"0","county":"Putnam","state":"New York"},
  {"slug":"rockland-newyork","cases":"3321","deaths":"29","county":"Rockland","state":"New York"},
  {"slug":"suffolk-newyork","cases":"7605","deaths":"69","county":"Suffolk","state":"New York"},
  {"slug":"ulster-newyork","cases":"222","deaths":"3","county":"Ulster","state":"New York"},
  {"slug":"westchester-newyork","cases":"10683","deaths":"25","county":"Westchester","state":"New York"},
  {"slug":"mecklenburg-northcarolina","cases":"444","deaths":"2","county":"Mecklenburg","state":"North Carolina"},
  {"slug":"cuyahoga-ohio","cases":"589","deaths":"9","county":"Cuyahoga","state":"Ohio"},
  {"slug":"franklin-ohio","cases":"391","deaths":"4","county":"Franklin","state":"Ohio"},
  {"slug":"allegheny-pennsylvania","cases":"356","deaths":"2","county":"Allegheny","state":"Pennsylvania"},
  {"slug":"bucks-pennsylvania","cases":"319","deaths":"6","county":"Bucks","state":"Pennsylvania"},
  {"slug":"delaware-pennsylvania","cases":"390","deaths":"7","county":"Delaware","state":"Pennsylvania"},
  {"slug":"lehigh-pennsylvania","cases":"374","deaths":"5","county":"Lehigh","state":"Pennsylvania"},
  {"slug":"luzerne-pennsylvania","cases":"282","deaths":"4","county":"Luzerne","state":"Pennsylvania"},
  {"slug":"monroe-pennsylvania","cases":"278","deaths":"8","county":"Monroe","state":"Pennsylvania"},
  {"slug":"montgomery-pennsylvania","cases":"649","deaths":"8","county":"Montgomery","state":"Pennsylvania"},
  {"slug":"northampton-pennsylvania","cases":"312","deaths":"5","county":"Northampton","state":"Pennsylvania"},
  {"slug":"philadelphia-pennsylvania","cases":"1478","deaths":"14","county":"Philadelphia","state":"Pennsylvania"},
  {"slug":"unknown-puertorico","cases":"286","deaths":"11","county":"Unknown","state":"Puerto Rico"},
  {"slug":"providence-rhodeisland","cases":"391","deaths":"3","county":"Providence","state":"Rhode Island"},
  {"slug":"davidson-tennessee","cases":"673","deaths":"4","county":"Davidson","state":"Tennessee"},
  {"slug":"shelby-tennessee","cases":"496","deaths":"3","county":"Shelby","state":"Tennessee"},
  {"slug":"sumner-tennessee","cases":"201","deaths":"7","county":"Sumner","state":"Tennessee"},
  {"slug":"unknown-tennessee","cases":"307","deaths":"17","county":"Unknown","state":"Tennessee"},
  {"slug":"bexar-texas","cases":"207","deaths":"9","county":"Bexar","state":"Texas"},
  {"slug":"dallas-texas","cases":"631","deaths":"13","county":"Dallas","state":"Texas"},
  {"slug":"denton-texas","cases":"206","deaths":"4","county":"Denton","state":"Texas"},
  {"slug":"harris-texas","cases":"847","deaths":"6","county":"Harris","state":"Texas"},
  {"slug":"tarrant-texas","cases":"288","deaths":"3","county":"Tarrant","state":"Texas"},
  {"slug":"travis-texas","cases":"244","deaths":"2","county":"Travis","state":"Texas"},
  {"slug":"saltlake-utah","cases":"396","deaths":"1","county":"Salt Lake","state":"Utah"},
  {"slug":"fairfax-virginia","cases":"288","deaths":"5","county":"Fairfax","state":"Virginia"},
  {"slug":"king-washington","cases":"2498","deaths":"166","county":"King","state":"Washington"},
  {"slug":"pierce-washington","cases":"423","deaths":"7","county":"Pierce","state":"Washington"},
  {"slug":"snohomish-washington","cases":"1304","deaths":"39","county":"Snohomish","state":"Washington"},
  {"slug":"yakima-washington","cases":"200","deaths":"3","county":"Yakima","state":"Washington"},
  {"slug":"dane-wisconsin","cases":"215","deaths":"2","county":"Dane","state":"Wisconsin"},
  {"slug":"milwaukee-wisconsin","cases":"780","deaths":"16","county":"Milwaukee","state":"Wisconsin"}
  ]  

export default counties;