// Ordinarily, you'd generate this data from markdown files in your
// repo, or fetch them from a database of some kind. But in order to
// avoid unnecessary dependencies in the starter template, and in the
// service of obviousness, we're just going to leave it here.

// This file is called `_posts.js` rather than `posts.js`, because
// we don't want to create an `/blog/posts` route — the leading
// underscore tells Sapper not to do that.

const counties = [
  {"slug":"jefferson-alabama","cases":"579","deaths":"15","county":"Jefferson","state":"Alabama"},
  {"slug":"lee-alabama","cases":"221","deaths":"8","county":"Lee","state":"Alabama"},
  {"slug":"mobile-alabama","cases":"429","deaths":"15","county":"Mobile","state":"Alabama"},
  {"slug":"coconino-arizona","cases":"238","deaths":"15","county":"Coconino","state":"Arizona"},
  {"slug":"maricopa-arizona","cases":"1891","deaths":"47","county":"Maricopa","state":"Arizona"},
  {"slug":"navajo-arizona","cases":"321","deaths":"7","county":"Navajo","state":"Arizona"},
  {"slug":"pima-arizona","cases":"591","deaths":"29","county":"Pima","state":"Arizona"},
  {"slug":"pulaski-arkansas","cases":"249","deaths":"9","county":"Pulaski","state":"Arkansas"},
  {"slug":"alameda-california","cases":"827","deaths":"21","county":"Alameda","state":"California"},
  {"slug":"contracosta-california","cases":"530","deaths":"11","county":"Contra Costa","state":"California"},
  {"slug":"fresno-california","cases":"201","deaths":"5","county":"Fresno","state":"California"},
  {"slug":"kern-california","cases":"369","deaths":"3","county":"Kern","state":"California"},
  {"slug":"losangeles-california","cases":"8873","deaths":"265","county":"Los Angeles","state":"California"},
  {"slug":"orange-california","cases":"1221","deaths":"18","county":"Orange","state":"California"},
  {"slug":"riverside-california","cases":"1431","deaths":"41","county":"Riverside","state":"California"},
  {"slug":"sacramento-california","cases":"699","deaths":"26","county":"Sacramento","state":"California"},
  {"slug":"sanbernardino-california","cases":"810","deaths":"25","county":"San Bernardino","state":"California"},
  {"slug":"sandiego-california","cases":"1761","deaths":"45","county":"San Diego","state":"California"},
  {"slug":"sanfrancisco-california","cases":"860","deaths":"13","county":"San Francisco","state":"California"},
  {"slug":"sanjoaquin-california","cases":"260","deaths":"15","county":"San Joaquin","state":"California"},
  {"slug":"sanmateo-california","cases":"652","deaths":"21","county":"San Mateo","state":"California"},
  {"slug":"santabarbara-california","cases":"264","deaths":"2","county":"Santa Barbara","state":"California"},
  {"slug":"santaclara-california","cases":"1566","deaths":"52","county":"Santa Clara","state":"California"},
  {"slug":"tulare-california","cases":"227","deaths":"11","county":"Tulare","state":"California"},
  {"slug":"ventura-california","cases":"309","deaths":"10","county":"Ventura","state":"California"},
  {"slug":"adams-colorado","cases":"593","deaths":"25","county":"Adams","state":"Colorado"},
  {"slug":"arapahoe-colorado","cases":"998","deaths":"37","county":"Arapahoe","state":"Colorado"},
  {"slug":"boulder-colorado","cases":"246","deaths":"8","county":"Boulder","state":"Colorado"},
  {"slug":"denver-colorado","cases":"1182","deaths":"46","county":"Denver","state":"Colorado"},
  {"slug":"douglas-colorado","cases":"292","deaths":"10","county":"Douglas","state":"Colorado"},
  {"slug":"eagle-colorado","cases":"433","deaths":"5","county":"Eagle","state":"Colorado"},
  {"slug":"elpaso-colorado","cases":"578","deaths":"35","county":"El Paso","state":"Colorado"},
  {"slug":"jefferson-colorado","cases":"713","deaths":"25","county":"Jefferson","state":"Colorado"},
  {"slug":"weld-colorado","cases":"683","deaths":"44","county":"Weld","state":"Colorado"},
  {"slug":"fairfield-connecticut","cases":"5407","deaths":"220","county":"Fairfield","state":"Connecticut"},
  {"slug":"hartford-connecticut","cases":"1832","deaths":"101","county":"Hartford","state":"Connecticut"},
  {"slug":"litchfield-connecticut","cases":"388","deaths":"20","county":"Litchfield","state":"Connecticut"},
  {"slug":"middlesex-connecticut","cases":"290","deaths":"18","county":"Middlesex","state":"Connecticut"},
  {"slug":"newhaven-connecticut","cases":"2715","deaths":"107","county":"New Haven","state":"Connecticut"},
  {"slug":"unknown-connecticut","cases":"456","deaths":"5","county":"Unknown","state":"Connecticut"},
  {"slug":"kent-delaware","cases":"255","deaths":"4","county":"Kent","state":"Delaware"},
  {"slug":"newcastle-delaware","cases":"807","deaths":"19","county":"New Castle","state":"Delaware"},
  {"slug":"sussex-delaware","cases":"404","deaths":"10","county":"Sussex","state":"Delaware"},
  {"slug":"districtofcolumbia-districtofcolumbia","cases":"1778","deaths":"47","county":"District of Columbia","state":"District of Columbia"},
  {"slug":"broward-florida","cases":"2844","deaths":"76","county":"Broward","state":"Florida"},
  {"slug":"collier-florida","cases":"352","deaths":"4","county":"Collier","state":"Florida"},
  {"slug":"duval-florida","cases":"639","deaths":"13","county":"Duval","state":"Florida"},
  {"slug":"escambia-florida","cases":"210","deaths":"3","county":"Escambia","state":"Florida"},
  {"slug":"hillsborough-florida","cases":"698","deaths":"15","county":"Hillsborough","state":"Florida"},
  {"slug":"lee-florida","cases":"597","deaths":"16","county":"Lee","state":"Florida"},
  {"slug":"manatee-florida","cases":"221","deaths":"13","county":"Manatee","state":"Florida"},
  {"slug":"miami-dade-florida","cases":"6757","deaths":"93","county":"Miami-Dade","state":"Florida"},
  {"slug":"orange-florida","cases":"922","deaths":"12","county":"Orange","state":"Florida"},
  {"slug":"osceola-florida","cases":"317","deaths":"5","county":"Osceola","state":"Florida"},
  {"slug":"palmbeach-florida","cases":"1499","deaths":"80","county":"Palm Beach","state":"Florida"},
  {"slug":"pinellas-florida","cases":"446","deaths":"12","county":"Pinellas","state":"Florida"},
  {"slug":"polk-florida","cases":"244","deaths":"8","county":"Polk","state":"Florida"},
  {"slug":"sarasota-florida","cases":"223","deaths":"12","county":"Sarasota","state":"Florida"},
  {"slug":"seminole-florida","cases":"242","deaths":"2","county":"Seminole","state":"Florida"},
  {"slug":"bartow-georgia","cases":"211","deaths":"15","county":"Bartow","state":"Georgia"},
  {"slug":"carroll-georgia","cases":"204","deaths":"5","county":"Carroll","state":"Georgia"},
  {"slug":"clayton-georgia","cases":"339","deaths":"11","county":"Clayton","state":"Georgia"},
  {"slug":"cobb-georgia","cases":"705","deaths":"32","county":"Cobb","state":"Georgia"},
  {"slug":"dekalb-georgia","cases":"848","deaths":"14","county":"DeKalb","state":"Georgia"},
  {"slug":"dougherty-georgia","cases":"1102","deaths":"72","county":"Dougherty","state":"Georgia"},
  {"slug":"fulton-georgia","cases":"1446","deaths":"50","county":"Fulton","state":"Georgia"},
  {"slug":"gwinnett-georgia","cases":"681","deaths":"18","county":"Gwinnett","state":"Georgia"},
  {"slug":"hall-georgia","cases":"276","deaths":"0","county":"Hall","state":"Georgia"},
  {"slug":"henry-georgia","cases":"254","deaths":"3","county":"Henry","state":"Georgia"},
  {"slug":"lee-georgia","cases":"236","deaths":"15","county":"Lee","state":"Georgia"},
  {"slug":"sumter-georgia","cases":"224","deaths":"9","county":"Sumter","state":"Georgia"},
  {"slug":"unknown-georgia","cases":"1300","deaths":"4","county":"Unknown","state":"Georgia"},
  {"slug":"unknown-guam","cases":"681","deaths":"5","county":"Unknown","state":"Guam"},
  {"slug":"honolulu-hawaii","cases":"348","deaths":"5","county":"Honolulu","state":"Hawaii"},
  {"slug":"ada-idaho","cases":"517","deaths":"6","county":"Ada","state":"Idaho"},
  {"slug":"blaine-idaho","cases":"454","deaths":"5","county":"Blaine","state":"Idaho"},
  {"slug":"cook-illinois","cases":"13417","deaths":"453","county":"Cook","state":"Illinois"},
  {"slug":"dupage-illinois","cases":"1048","deaths":"48","county":"DuPage","state":"Illinois"},
  {"slug":"kane-illinois","cases":"376","deaths":"22","county":"Kane","state":"Illinois"},
  {"slug":"lake-illinois","cases":"1331","deaths":"39","county":"Lake","state":"Illinois"},
  {"slug":"mchenry-illinois","cases":"220","deaths":"6","county":"McHenry","state":"Illinois"},
  {"slug":"will-illinois","cases":"1126","deaths":"56","county":"Will","state":"Illinois"},
  {"slug":"hamilton-indiana","cases":"443","deaths":"22","county":"Hamilton","state":"Indiana"},
  {"slug":"hendricks-indiana","cases":"301","deaths":"9","county":"Hendricks","state":"Indiana"},
  {"slug":"johnson-indiana","cases":"287","deaths":"19","county":"Johnson","state":"Indiana"},
  {"slug":"lake-indiana","cases":"676","deaths":"25","county":"Lake","state":"Indiana"},
  {"slug":"madison-indiana","cases":"235","deaths":"13","county":"Madison","state":"Indiana"},
  {"slug":"marion-indiana","cases":"2742","deaths":"118","county":"Marion","state":"Indiana"},
  {"slug":"linn-iowa","cases":"235","deaths":"12","county":"Linn","state":"Iowa"},
  {"slug":"johnson-kansas","cases":"283","deaths":"13","county":"Johnson","state":"Kansas"},
  {"slug":"wyandotte-kansas","cases":"315","deaths":"24","county":"Wyandotte","state":"Kansas"},
  {"slug":"jefferson-kentucky","cases":"495","deaths":"40","county":"Jefferson","state":"Kentucky"},
  {"slug":"ascension-louisiana","cases":"415","deaths":"20","county":"Ascension","state":"Louisiana"},
  {"slug":"caddo-louisiana","cases":"974","deaths":"39","county":"Caddo","state":"Louisiana"},
  {"slug":"calcasieu-louisiana","cases":"248","deaths":"8","county":"Calcasieu","state":"Louisiana"},
  {"slug":"eastbatonrouge-louisiana","cases":"1158","deaths":"45","county":"East Baton Rouge","state":"Louisiana"},
  {"slug":"iberville-louisiana","cases":"214","deaths":"12","county":"Iberville","state":"Louisiana"},
  {"slug":"jefferson-louisiana","cases":"4877","deaths":"170","county":"Jefferson","state":"Louisiana"},
  {"slug":"lafayette-louisiana","cases":"337","deaths":"12","county":"Lafayette","state":"Louisiana"},
  {"slug":"lafourche-louisiana","cases":"454","deaths":"13","county":"Lafourche","state":"Louisiana"},
  {"slug":"orleans-louisiana","cases":"5535","deaths":"232","county":"Orleans","state":"Louisiana"},
  {"slug":"ouachita-louisiana","cases":"350","deaths":"5","county":"Ouachita","state":"Louisiana"},
  {"slug":"st.bernard-louisiana","cases":"358","deaths":"10","county":"St. Bernard","state":"Louisiana"},
  {"slug":"st.charles-louisiana","cases":"401","deaths":"24","county":"St. Charles","state":"Louisiana"},
  {"slug":"st.johnthebaptist-louisiana","cases":"538","deaths":"38","county":"St. John the Baptist","state":"Louisiana"},
  {"slug":"st.tammany-louisiana","cases":"845","deaths":"32","county":"St. Tammany","state":"Louisiana"},
  {"slug":"tangipahoa-louisiana","cases":"318","deaths":"7","county":"Tangipahoa","state":"Louisiana"},
  {"slug":"terrebonne-louisiana","cases":"248","deaths":"14","county":"Terrebonne","state":"Louisiana"},
  {"slug":"cumberland-maine","cases":"284","deaths":"12","county":"Cumberland","state":"Maine"},
  {"slug":"annearundel-maryland","cases":"615","deaths":"19","county":"Anne Arundel","state":"Maryland"},
  {"slug":"baltimore-maryland","cases":"1173","deaths":"26","county":"Baltimore","state":"Maryland"},
  {"slug":"baltimorecity-maryland","cases":"756","deaths":"22","county":"Baltimore city","state":"Maryland"},
  {"slug":"carroll-maryland","cases":"214","deaths":"25","county":"Carroll","state":"Maryland"},
  {"slug":"charles-maryland","cases":"235","deaths":"5","county":"Charles","state":"Maryland"},
  {"slug":"frederick-maryland","cases":"341","deaths":"11","county":"Frederick","state":"Maryland"},
  {"slug":"howard-maryland","cases":"351","deaths":"6","county":"Howard","state":"Maryland"},
  {"slug":"montgomery-maryland","cases":"1537","deaths":"36","county":"Montgomery","state":"Maryland"},
  {"slug":"princegeorge's-maryland","cases":"1923","deaths":"50","county":"Prince George's","state":"Maryland"},
  {"slug":"barnstable-massachusetts","cases":"480","deaths":"15","county":"Barnstable","state":"Massachusetts"},
  {"slug":"berkshire-massachusetts","cases":"336","deaths":"22","county":"Berkshire","state":"Massachusetts"},
  {"slug":"bristol-massachusetts","cases":"1191","deaths":"39","county":"Bristol","state":"Massachusetts"},
  {"slug":"essex-massachusetts","cases":"2896","deaths":"91","county":"Essex","state":"Massachusetts"},
  {"slug":"hampden-massachusetts","cases":"1545","deaths":"95","county":"Hampden","state":"Massachusetts"},
  {"slug":"hampshire-massachusetts","cases":"204","deaths":"4","county":"Hampshire","state":"Massachusetts"},
  {"slug":"middlesex-massachusetts","cases":"4872","deaths":"137","county":"Middlesex","state":"Massachusetts"},
  {"slug":"norfolk-massachusetts","cases":"2395","deaths":"79","county":"Norfolk","state":"Massachusetts"},
  {"slug":"plymouth-massachusetts","cases":"1809","deaths":"57","county":"Plymouth","state":"Massachusetts"},
  {"slug":"suffolk-massachusetts","cases":"4926","deaths":"74","county":"Suffolk","state":"Massachusetts"},
  {"slug":"unknown-massachusetts","cases":"225","deaths":"9","county":"Unknown","state":"Massachusetts"},
  {"slug":"worcester-massachusetts","cases":"1822","deaths":"41","county":"Worcester","state":"Massachusetts"},
  {"slug":"genesee-michigan","cases":"919","deaths":"62","county":"Genesee","state":"Michigan"},
  {"slug":"ingham-michigan","cases":"241","deaths":"3","county":"Ingham","state":"Michigan"},
  {"slug":"kent-michigan","cases":"270","deaths":"13","county":"Kent","state":"Michigan"},
  {"slug":"livingston-michigan","cases":"206","deaths":"3","county":"Livingston","state":"Michigan"},
  {"slug":"macomb-michigan","cases":"3164","deaths":"209","county":"Macomb","state":"Michigan"},
  {"slug":"oakland-michigan","cases":"4802","deaths":"316","county":"Oakland","state":"Michigan"},
  {"slug":"saginaw-michigan","cases":"254","deaths":"9","county":"Saginaw","state":"Michigan"},
  {"slug":"unknown-michigan","cases":"474","deaths":"15","county":"Unknown","state":"Michigan"},
  {"slug":"washtenaw-michigan","cases":"685","deaths":"18","county":"Washtenaw","state":"Michigan"},
  {"slug":"wayne-michigan","cases":"10951","deaths":"652","county":"Wayne","state":"Michigan"},
  {"slug":"hennepin-minnesota","cases":"464","deaths":"30","county":"Hennepin","state":"Minnesota"},
  {"slug":"hinds-mississippi","cases":"234","deaths":"2","county":"Hinds","state":"Mississippi"},
  {"slug":"jackson-missouri","cases":"208","deaths":"7","county":"Jackson","state":"Missouri"},
  {"slug":"kansascity-missouri","cases":"298","deaths":"8","county":"Kansas City","state":"Missouri"},
  {"slug":"st.charles-missouri","cases":"320","deaths":"11","county":"St. Charles","state":"Missouri"},
  {"slug":"st.louis-missouri","cases":"1568","deaths":"42","county":"St. Louis","state":"Missouri"},
  {"slug":"st.louiscity-missouri","cases":"585","deaths":"17","county":"St. Louis city","state":"Missouri"},
  {"slug":"douglas-nebraska","cases":"254","deaths":"7","county":"Douglas","state":"Nebraska"},
  {"slug":"clark-nevada","cases":"2258","deaths":"96","county":"Clark","state":"Nevada"},
  {"slug":"washoe-nevada","cases":"389","deaths":"11","county":"Washoe","state":"Nevada"},
  {"slug":"hillsborough-newhampshire","cases":"367","deaths":"15","county":"Hillsborough","state":"New Hampshire"},
  {"slug":"rockingham-newhampshire","cases":"314","deaths":"3","county":"Rockingham","state":"New Hampshire"},
  {"slug":"atlantic-newjersey","cases":"230","deaths":"7","county":"Atlantic","state":"New Jersey"},
  {"slug":"bergen-newjersey","cases":"9362","deaths":"435","county":"Bergen","state":"New Jersey"},
  {"slug":"burlington-newjersey","cases":"1031","deaths":"22","county":"Burlington","state":"New Jersey"},
  {"slug":"camden-newjersey","cases":"1180","deaths":"29","county":"Camden","state":"New Jersey"},
  {"slug":"essex-newjersey","cases":"7007","deaths":"412","county":"Essex","state":"New Jersey"},
  {"slug":"gloucester-newjersey","cases":"487","deaths":"9","county":"Gloucester","state":"New Jersey"},
  {"slug":"hudson-newjersey","cases":"6851","deaths":"183","county":"Hudson","state":"New Jersey"},
  {"slug":"hunterdon-newjersey","cases":"301","deaths":"11","county":"Hunterdon","state":"New Jersey"},
  {"slug":"mercer-newjersey","cases":"1434","deaths":"49","county":"Mercer","state":"New Jersey"},
  {"slug":"middlesex-newjersey","cases":"5406","deaths":"177","county":"Middlesex","state":"New Jersey"},
  {"slug":"monmouth-newjersey","cases":"3651","deaths":"115","county":"Monmouth","state":"New Jersey"},
  {"slug":"morris-newjersey","cases":"2925","deaths":"152","county":"Morris","state":"New Jersey"},
  {"slug":"ocean-newjersey","cases":"3403","deaths":"132","county":"Ocean","state":"New Jersey"},
  {"slug":"passaic-newjersey","cases":"5295","deaths":"119","county":"Passaic","state":"New Jersey"},
  {"slug":"somerset-newjersey","cases":"1642","deaths":"78","county":"Somerset","state":"New Jersey"},
  {"slug":"sussex-newjersey","cases":"456","deaths":"27","county":"Sussex","state":"New Jersey"},
  {"slug":"union-newjersey","cases":"5865","deaths":"195","county":"Union","state":"New Jersey"},
  {"slug":"unknown-newjersey","cases":"924","deaths":"2","county":"Unknown","state":"New Jersey"},
  {"slug":"warren-newjersey","cases":"362","deaths":"18","county":"Warren","state":"New Jersey"},
  {"slug":"bernalillo-newmexico","cases":"422","deaths":"13","county":"Bernalillo","state":"New Mexico"},
  {"slug":"albany-newyork","cases":"446","deaths":"16","county":"Albany","state":"New York"},
  {"slug":"dutchess-newyork","cases":"1744","deaths":"27","county":"Dutchess","state":"New York"},
  {"slug":"erie-newyork","cases":"1472","deaths":"62","county":"Erie","state":"New York"},
  {"slug":"monroe-newyork","cases":"767","deaths":"42","county":"Monroe","state":"New York"},
  {"slug":"nassau-newyork","cases":"22584","deaths":"965","county":"Nassau","state":"New York"},
  {"slug":"newyorkcity-newyork","cases":"98308","deaths":"6202","county":"New York City","state":"New York"},
  {"slug":"onondaga-newyork","cases":"380","deaths":"12","county":"Onondaga","state":"New York"},
  {"slug":"orange-newyork","cases":"4847","deaths":"99","county":"Orange","state":"New York"},
  {"slug":"putnam-newyork","cases":"494","deaths":"20","county":"Putnam","state":"New York"},
  {"slug":"rockland-newyork","cases":"7477","deaths":"153","county":"Rockland","state":"New York"},
  {"slug":"suffolk-newyork","cases":"19883","deaths":"469","county":"Suffolk","state":"New York"},
  {"slug":"sullivan-newyork","cases":"340","deaths":"7","county":"Sullivan","state":"New York"},
  {"slug":"ulster-newyork","cases":"589","deaths":"2","county":"Ulster","state":"New York"},
  {"slug":"westchester-newyork","cases":"18729","deaths":"505","county":"Westchester","state":"New York"},
  {"slug":"durham-northcarolina","cases":"275","deaths":"1","county":"Durham","state":"North Carolina"},
  {"slug":"mecklenburg-northcarolina","cases":"935","deaths":"12","county":"Mecklenburg","state":"North Carolina"},
  {"slug":"wake-northcarolina","cases":"424","deaths":"0","county":"Wake","state":"North Carolina"},
  {"slug":"cuyahoga-ohio","cases":"1113","deaths":"22","county":"Cuyahoga","state":"Ohio"},
  {"slug":"franklin-ohio","cases":"894","deaths":"14","county":"Franklin","state":"Ohio"},
  {"slug":"hamilton-ohio","cases":"529","deaths":"17","county":"Hamilton","state":"Ohio"},
  {"slug":"lucas-ohio","cases":"490","deaths":"21","county":"Lucas","state":"Ohio"},
  {"slug":"mahoning-ohio","cases":"375","deaths":"31","county":"Mahoning","state":"Ohio"},
  {"slug":"summit-ohio","cases":"243","deaths":"14","county":"Summit","state":"Ohio"},
  {"slug":"cleveland-oklahoma","cases":"247","deaths":"17","county":"Cleveland","state":"Oklahoma"},
  {"slug":"oklahoma-oklahoma","cases":"425","deaths":"19","county":"Oklahoma","state":"Oklahoma"},
  {"slug":"tulsa-oklahoma","cases":"323","deaths":"16","county":"Tulsa","state":"Oklahoma"},
  {"slug":"marion-oregon","cases":"263","deaths":"9","county":"Marion","state":"Oregon"},
  {"slug":"multnomah-oregon","cases":"343","deaths":"18","county":"Multnomah","state":"Oregon"},
  {"slug":"washington-oregon","cases":"330","deaths":"6","county":"Washington","state":"Oregon"},
  {"slug":"allegheny-pennsylvania","cases":"836","deaths":"19","county":"Allegheny","state":"Pennsylvania"},
  {"slug":"berks-pennsylvania","cases":"930","deaths":"19","county":"Berks","state":"Pennsylvania"},
  {"slug":"bucks-pennsylvania","cases":"1170","deaths":"35","county":"Bucks","state":"Pennsylvania"},
  {"slug":"chester-pennsylvania","cases":"532","deaths":"15","county":"Chester","state":"Pennsylvania"},
  {"slug":"dauphin-pennsylvania","cases":"213","deaths":"3","county":"Dauphin","state":"Pennsylvania"},
  {"slug":"delaware-pennsylvania","cases":"1510","deaths":"39","county":"Delaware","state":"Pennsylvania"},
  {"slug":"lackawanna-pennsylvania","cases":"392","deaths":"20","county":"Lackawanna","state":"Pennsylvania"},
  {"slug":"lancaster-pennsylvania","cases":"698","deaths":"23","county":"Lancaster","state":"Pennsylvania"},
  {"slug":"lebanon-pennsylvania","cases":"232","deaths":"1","county":"Lebanon","state":"Pennsylvania"},
  {"slug":"lehigh-pennsylvania","cases":"1620","deaths":"16","county":"Lehigh","state":"Pennsylvania"},
  {"slug":"luzerne-pennsylvania","cases":"1372","deaths":"17","county":"Luzerne","state":"Pennsylvania"},
  {"slug":"monroe-pennsylvania","cases":"774","deaths":"22","county":"Monroe","state":"Pennsylvania"},
  {"slug":"montgomery-pennsylvania","cases":"2053","deaths":"68","county":"Montgomery","state":"Pennsylvania"},
  {"slug":"northampton-pennsylvania","cases":"1039","deaths":"23","county":"Northampton","state":"Pennsylvania"},
  {"slug":"philadelphia-pennsylvania","cases":"6022","deaths":"130","county":"Philadelphia","state":"Pennsylvania"},
  {"slug":"pike-pennsylvania","cases":"208","deaths":"6","county":"Pike","state":"Pennsylvania"},
  {"slug":"westmoreland-pennsylvania","cases":"218","deaths":"12","county":"Westmoreland","state":"Pennsylvania"},
  {"slug":"york-pennsylvania","cases":"293","deaths":"3","county":"York","state":"Pennsylvania"},
  {"slug":"unknown-puertorico","cases":"788","deaths":"42","county":"Unknown","state":"Puerto Rico"},
  {"slug":"providence-rhodeisland","cases":"1278","deaths":"20","county":"Providence","state":"Rhode Island"},
  {"slug":"unknown-rhodeisland","cases":"673","deaths":"36","county":"Unknown","state":"Rhode Island"},
  {"slug":"charleston-southcarolina","cases":"331","deaths":"1","county":"Charleston","state":"South Carolina"},
  {"slug":"greenville-southcarolina","cases":"325","deaths":"7","county":"Greenville","state":"South Carolina"},
  {"slug":"lexington-southcarolina","cases":"202","deaths":"6","county":"Lexington","state":"South Carolina"},
  {"slug":"richland-southcarolina","cases":"479","deaths":"10","county":"Richland","state":"South Carolina"},
  {"slug":"minnehaha-southdakota","cases":"438","deaths":"2","county":"Minnehaha","state":"South Dakota"},
  {"slug":"davidson-tennessee","cases":"1256","deaths":"13","county":"Davidson","state":"Tennessee"},
  {"slug":"rutherford-tennessee","cases":"235","deaths":"6","county":"Rutherford","state":"Tennessee"},
  {"slug":"shelby-tennessee","cases":"1147","deaths":"26","county":"Shelby","state":"Tennessee"},
  {"slug":"sumner-tennessee","cases":"435","deaths":"22","county":"Sumner","state":"Tennessee"},
  {"slug":"williamson-tennessee","cases":"312","deaths":"4","county":"Williamson","state":"Tennessee"},
  {"slug":"bexar-texas","cases":"723","deaths":"24","county":"Bexar","state":"Texas"},
  {"slug":"brazoria-texas","cases":"225","deaths":"2","county":"Brazoria","state":"Texas"},
  {"slug":"collin-texas","cases":"441","deaths":"7","county":"Collin","state":"Texas"},
  {"slug":"dallas-texas","cases":"1648","deaths":"27","county":"Dallas","state":"Texas"},
  {"slug":"denton-texas","cases":"454","deaths":"10","county":"Denton","state":"Texas"},
  {"slug":"elpaso-texas","cases":"269","deaths":"2","county":"El Paso","state":"Texas"},
  {"slug":"fortbend-texas","cases":"518","deaths":"11","county":"Fort Bend","state":"Texas"},
  {"slug":"galveston-texas","cases":"355","deaths":"8","county":"Galveston","state":"Texas"},
  {"slug":"harris-texas","cases":"3561","deaths":"41","county":"Harris","state":"Texas"},
  {"slug":"lubbock-texas","cases":"270","deaths":"13","county":"Lubbock","state":"Texas"},
  {"slug":"montgomery-texas","cases":"245","deaths":"4","county":"Montgomery","state":"Texas"},
  {"slug":"tarrant-texas","cases":"705","deaths":"21","county":"Tarrant","state":"Texas"},
  {"slug":"travis-texas","cases":"690","deaths":"9","county":"Travis","state":"Texas"},
  {"slug":"saltlake-utah","cases":"1071","deaths":"7","county":"Salt Lake","state":"Utah"},
  {"slug":"summit-utah","cases":"300","deaths":"0","county":"Summit","state":"Utah"},
  {"slug":"utah-utah","cases":"295","deaths":"0","county":"Utah","state":"Utah"},
  {"slug":"chittenden-vermont","cases":"351","deaths":"16","county":"Chittenden","state":"Vermont"},
  {"slug":"arlington-virginia","cases":"349","deaths":"2","county":"Arlington","state":"Virginia"},
  {"slug":"chesterfield-virginia","cases":"203","deaths":"0","county":"Chesterfield","state":"Virginia"},
  {"slug":"fairfax-virginia","cases":"946","deaths":"16","county":"Fairfax","state":"Virginia"},
  {"slug":"henrico-virginia","cases":"368","deaths":"35","county":"Henrico","state":"Virginia"},
  {"slug":"loudoun-virginia","cases":"296","deaths":"0","county":"Loudoun","state":"Virginia"},
  {"slug":"princewilliam-virginia","cases":"390","deaths":"1","county":"Prince William","state":"Virginia"},
  {"slug":"virginiabeachcity-virginia","cases":"236","deaths":"1","county":"Virginia Beach city","state":"Virginia"},
  {"slug":"benton-washington","cases":"246","deaths":"26","county":"Benton","state":"Washington"},
  {"slug":"clark-washington","cases":"220","deaths":"14","county":"Clark","state":"Washington"},
  {"slug":"king-washington","cases":"4264","deaths":"286","county":"King","state":"Washington"},
  {"slug":"pierce-washington","cases":"928","deaths":"19","county":"Pierce","state":"Washington"},
  {"slug":"snohomish-washington","cases":"1834","deaths":"67","county":"Snohomish","state":"Washington"},
  {"slug":"spokane-washington","cases":"255","deaths":"14","county":"Spokane","state":"Washington"},
  {"slug":"whatcom-washington","cases":"252","deaths":"23","county":"Whatcom","state":"Washington"},
  {"slug":"yakima-washington","cases":"535","deaths":"21","county":"Yakima","state":"Washington"},
  {"slug":"dane-wisconsin","cases":"327","deaths":"12","county":"Dane","state":"Wisconsin"},
  {"slug":"milwaukee-wisconsin","cases":"1653","deaths":"85","county":"Milwaukee","state":"Wisconsin"},
  {"slug":"waukesha-wisconsin","cases":"201","deaths":"6","county":"Waukesha","state":"Wisconsin"},
  {"slug":"unknown-washington","cases":"583","deaths":"0","county":"Unknown","state":"Washington"}
]     

export default counties;