// Ordinarily, you'd generate this data from markdown files in your
// repo, or fetch them from a database of some kind. But in order to
// avoid unnecessary dependencies in the starter template, and in the
// service of obviousness, we're just going to leave it here.

// This file is called `_posts.js` rather than `posts.js`, because
// we don't want to create an `/blog/posts` route — the leading
// underscore tells Sapper not to do that.

const posts = [
  {"title":"The COVID Tracking Project","description":"The COVID Tracking Project collects information from 50 US states, the District of Columbia, and 5 other US territories to provide the most comprehensive testing data we can collect for the novel coronavirus, SARS-CoV-2. We attempt to include positive and negative results, pending tests, and total people tested for each state or district currently reporting that data.","url":"https://covidtracking.com/","email":"","social":"","tags":"Tracking and Tracing,Digital Applications","region":"National","city":""},
  {"title":"Open Collective Fiscal Sponsorhip","description":"For the next 3 months (till the end of June), we are removing our 5% fiscal sponsorship fee. Open Collective is also removing their 5% platform fee during this crisis. So it will be free for all those collectives to receive and disburse money.","url":"https://opencollective.com/foundation/updates/we-are-offering-free-fiscal-sponsorship-for-covid19-related-collectives","email":"","social":"","tags":"Community Orgs,Treatment and Prevention","region":"National","city":""},
  {"title":"Covid Act Now","description":"","url":"http://covidactnow.org","email":"jonathan@covidactnow.org","social":"","tags":"Epidemiology and Data,Policy Proposals","region":"National","city":""},
  {"title":"Masks for Docs","description":"","url":"https://masksfordocs.com/","email":"","social":"https://twitter.com/MasksForDocs","tags":"Mutual Aid,Community Orgs,Volunteer Opportunities","region":"National","city":""},
  {"title":"Project N95","description":"Rapid response teams have been coordinating with manufacturers globally with the capacity to produce millions of NIOSH-approved N95 masks and other critical medical equipment.","url":"https://www.projectn95.com/","email":"info@projectn95.com","social":"","tags":"Mutual Aid,Community Orgs","region":"National","city":""},
  {"title":"US Digital Response","description":"If you work in government, and need top-notch, vetted help to get through the COVID-19 crisis, you’re in the right place. Just fill out this intake form and we’ll figure out the rest.","url":"https://www.usdigitalresponse.org/","email":"info@usdigitalresponse.org","social":"","tags":"Digital Applications,Governmental Orgs,Volunteer Opportunities","region":"National","city":""}
  ,
  {"title":"Coronavirus.gov","description":"Official clearing house for coronavirus news and alerts.","url":"https://www.coronavirus.gov/","email":"","social":"","tags":"Governmental Orgs","region":"National","city":""},
  {"title":"East Oakland Collective","description":"The East Oakland Collective provides food and other direct aid to some of our most vulnerable populations.","url":"http://www.eastoaklandcollective.com/","email":"","social":"https://twitter.com/eoakcollective","tags":"Mutual Aid,Treatment and Prevention,Financial Relief,Volunteer Opportunities","region":"California","city":"Oakland"},
  {"title":"Peoples Breakfast Oakland","description":"Peoples Breakfast Oakland provides mutual aid in the form of food, shelter, clothing and other advocacy for unhoused folks in West Oakland.","url":"https://linktr.ee/PBO","email":"","social":"https://twitter.com/peoplesbreakoak","tags":"Mutual Aid,Financial Relief,Volunteer Opportunities","region":"California","city":"Oakland"},
  {"title":"PopCare","description":"Popcare intends to provide a basic income of $1,000 per month to teachers, students, and workers who have been laid off due to COVID-19.","url":"https://popcare.co/","email":"","social":"https://twitter.com/pophirehq","tags":"Digital Applications,Financial Relief,Mutual Aid","region":"National","city":""},
  {"title":"Phat Beets Produce CSA","description":"Phat Beets Produce provides delivery of locally grown fruits and vegetables to food desert neighborhoods in Oakland and the broader East Bay.  They also have a generous pricing model that enables them to provide free access to undercapitalized folks.","url":"https://www.phatbeetsproduce.org","email":"","social":"https://twitter.com/turnipdembeets","tags":"Mutual Aid,Community Orgs","region":"California","city":"Oakland"},
  {"title":"National Association of County and City Health Officials","description":"NACCHO has created a tool to help you search for local health departments in your area. Find contact information for local health departments using the map below and check to see that your health department is listed correctly.","url":"https://www.naccho.org/membership/lhd-directory","email":"","social":"","tags":"Treatment and Prevention,Governmental Orgs","region":"National","city":""},
  {"title":"Together SF","description":"We are a group of San Franciscans connecting people and resources to soften the impact of COVID-19 on local businesses and our most vulnerable neighbors.","url":"https://www.togethersf.org/","email":"","social":"https://twitter.com/WeAreTogetherSF","tags":"Mutual Aid,Community Orgs","region":"California","city":"San Francisco"},
  {"title":"Berkeley Mutual Aid","description":"The Berkeley Mutual Aid Network is a platform to help neighbors connect during the Coronavirus pandemic so that no one in our community has to face this crisis alone.","url":"https://www.berkeleymutualaid.org/","email":"","social":"","tags":"Mutual Aid,Community Orgs","region":"California","city":"Berkeley"},
  {"title":"Berkeley Relief Fund","description":"Community coming together to support small businesses, arts nonprofits, and residential tenants during the COVID-19 pandemic. (donations are tax deductible)","url":"https://berkeleyrelieffund.org/","email":"","social":"https://twitter.com/hashtag/BerkeleyReliefFund?src=hash","tags":"Governmental Orgs,Financial Relief","region":"California","city":"Berkeley"}
]
  
export default posts;
